SELECT 
    CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS Full_Name, 
    C.CURRENT_JOB_TITLE, 

FROM 
    IT_RECRUITMENT.OPENINGS.CANDIDATES C
JOIN 
    IT_RECRUITMENT.OPENINGS.IT_ROLES I
ON 
    C.CURRENT_JOB_TITLE = I.Job_Title
WHERE 
    C.VISA_REQUIRED_EU = TRUE
