SELECT 
    C.FIRST_NAME, 
    C.LAST_NAME, 
    C.EMAIL_ID, 
    I.Job_Title, 
    I.Company
FROM 
    IT_RECRUITMENT.OPENINGS.CANDIDATES C
JOIN 
    IT_RECRUITMENT.OPENINGS.IT_ROLES I
ON 
    C.CURRENT_JOB_TITLE = I.Job_Title;
